=== alps-asd/app-state-diagram/alps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation source="https://alps.io/spec/index.html">
            A data format for defining simple descriptions of application-level semantics
        </xs:documentation>
        <xs:appinfo source="https://alps.io/spec/index.html"/>
    </xs:annotation>
    <xs:element name="alps" type="alpsType"/>
    <xs:complexType name="alpsType">
        <xs:annotation>
            <xs:documentation>
                A data format for defining simple descriptions of application-level semantics
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="doc" minOccurs="0"/>
                <xs:element ref="link" minOccurs="0"/>
                <xs:element ref="title" minOccurs="0"/>
                <xs:element ref="ext" minOccurs="0"/>
                <xs:element ref="descriptor"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string">
            <xs:annotation>
                <xs:documentation> Indicates the version of the ALPS specification used in the document. </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="version" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                Indicates the version of the ALPS specification used in the document.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="doc" type="docType">
        <xs:annotation>
            <xs:documentation>
                A text field that contains free-form, usually human-readable, text.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="title" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                Defines the semantics of specific data elements or state transitions that MAY exist in an associated
                representation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="descriptor" type="descriptorType">
        <xs:annotation>
            <xs:documentation>
                Defines the semantics of specific data elements or state transitions that MAY exist in an associated
                representation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="link" type="linkType">
        <xs:annotation>
            <xs:documentation>
                An element that identifies a link between the current ALPS element
                and some other (possibly external) resource.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="ext" type="extType">
        <xs:annotation>
            <xs:documentation>
                The 'ext' element can be used to extend the ALPS document with author-specific information.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="contentType" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                A media-type values registered with the IANA.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="descriptorType" mixed="true">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="descriptor" type="descriptorType" minOccurs="0"/>
                <xs:element name="doc" type="docType" minOccurs="0"/>
                <xs:element name="link" type="linkType" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
        <!-- documented attribute -->
        <xs:attribute name="href" type="xs:anyURI"/>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="semantic"/>
                    <xs:enumeration value="safe"/>
                    <xs:enumeration value="unsafe"/>
                    <xs:enumeration value="idempotent"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="doc" type="xs:string"/>
        <xs:attribute name="ext" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="rt" type="rtType"/>
        <xs:attribute name="def" type="xs:anyURI"/>
        <xs:attribute name="tag" type="xs:string"/>
        <xs:attribute name="rel" type="relType"/>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="extType">
        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    `ext` element extends the ALPS document with author-specific information.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="href" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="tag" type="xs:string"/>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="linkType">
        <xs:attribute name="rel" type="xs:string"/>
        <xs:attribute name="href" type="xs:anyURI"/>
        <xs:attribute name="tag" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="docType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="text"/>
                            <xs:enumeration value="html"/>
                            <xs:enumeration value="asciidoc"/>
                            <xs:enumeration value="markdown"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="contentType" type="xs:string" />
                <xs:attribute name="tag" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="rtType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*#.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="relType">
        <xs:union memberTypes="predefinedRelType strictUriType"/>
    </xs:simpleType>
    <xs:simpleType name="predefinedRelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="about"/>
            <xs:enumeration value="acl"/>
            <xs:enumeration value="alternate"/>
            <xs:enumeration value="amphtml"/>
            <xs:enumeration value="appendix"/>
            <xs:enumeration value="apple-touch-icon"/>
            <xs:enumeration value="apple-touch-startup-image"/>
            <xs:enumeration value="archives"/>
            <xs:enumeration value="author"/>
            <xs:enumeration value="blocked-by"/>
            <xs:enumeration value="bookmark"/>
            <xs:enumeration value="c2pa-manifest"/>
            <xs:enumeration value="canonical"/>
            <xs:enumeration value="chapter"/>
            <xs:enumeration value="cite-as"/>
            <xs:enumeration value="collection"/>
            <xs:enumeration value="compression-dictionary"/>
            <xs:enumeration value="contents"/>
            <xs:enumeration value="convertedfrom"/>
            <xs:enumeration value="copyright"/>
            <xs:enumeration value="create-form"/>
            <xs:enumeration value="current"/>
            <xs:enumeration value="describedby"/>
            <xs:enumeration value="describes"/>
            <xs:enumeration value="disclosure"/>
            <xs:enumeration value="dns-prefetch"/>
            <xs:enumeration value="duplicate"/>
            <xs:enumeration value="edit"/>
            <xs:enumeration value="edit-form"/>
            <xs:enumeration value="edit-media"/>
            <xs:enumeration value="enclosure"/>
            <xs:enumeration value="external"/>
            <xs:enumeration value="first"/>
            <xs:enumeration value="glossary"/>
            <xs:enumeration value="help"/>
            <xs:enumeration value="hosts"/>
            <xs:enumeration value="hub"/>
            <xs:enumeration value="ice-server"/>
            <xs:enumeration value="icon"/>
            <xs:enumeration value="index"/>
            <xs:enumeration value="intervalafter"/>
            <xs:enumeration value="intervalbefore"/>
            <xs:enumeration value="intervalcontains"/>
            <xs:enumeration value="intervaldisjoint"/>
            <xs:enumeration value="intervalduring"/>
            <xs:enumeration value="intervalequals"/>
            <xs:enumeration value="intervalfinishedby"/>
            <xs:enumeration value="intervalfinishes"/>
            <xs:enumeration value="intervalin"/>
            <xs:enumeration value="intervalmeets"/>
            <xs:enumeration value="intervalmetby"/>
            <xs:enumeration value="intervaloverlappedby"/>
            <xs:enumeration value="intervaloverlaps"/>
            <xs:enumeration value="intervalstartedby"/>
            <xs:enumeration value="intervalstarts"/>
            <xs:enumeration value="item"/>
            <xs:enumeration value="last"/>
            <xs:enumeration value="latest-version"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="linkset"/>
            <xs:enumeration value="lrdd"/>
            <xs:enumeration value="manifest"/>
            <xs:enumeration value="mask-icon"/>
            <xs:enumeration value="me"/>
            <xs:enumeration value="media-feed"/>
            <xs:enumeration value="memento"/>
            <xs:enumeration value="micropub"/>
            <xs:enumeration value="modulepreload"/>
            <xs:enumeration value="monitor"/>
            <xs:enumeration value="monitor-group"/>
            <xs:enumeration value="next"/>
            <xs:enumeration value="next-archive"/>
            <xs:enumeration value="nofollow"/>
            <xs:enumeration value="noopener"/>
            <xs:enumeration value="noreferrer"/>
            <xs:enumeration value="opener"/>
            <xs:enumeration value="openid2.local_id"/>
            <xs:enumeration value="openid2.provider"/>
            <xs:enumeration value="original"/>
            <xs:enumeration value="p3pv1"/>
            <xs:enumeration value="payment"/>
            <xs:enumeration value="pingback"/>
            <xs:enumeration value="preconnect"/>
            <xs:enumeration value="predecessor-version"/>
            <xs:enumeration value="prefetch"/>
            <xs:enumeration value="preload"/>
            <xs:enumeration value="prerender"/>
            <xs:enumeration value="prev"/>
            <xs:enumeration value="prev-archive"/>
            <xs:enumeration value="preview"/>
            <xs:enumeration value="previous"/>
            <xs:enumeration value="privacy-policy"/>
            <xs:enumeration value="profile"/>
            <xs:enumeration value="publication"/>
            <xs:enumeration value="related"/>
            <xs:enumeration value="replies"/>
            <xs:enumeration value="restconf"/>
            <xs:enumeration value="ruleinput"/>
            <xs:enumeration value="search"/>
            <xs:enumeration value="section"/>
            <xs:enumeration value="self"/>
            <xs:enumeration value="service"/>
            <xs:enumeration value="service-desc"/>
            <xs:enumeration value="service-doc"/>
            <xs:enumeration value="service-meta"/>
            <xs:enumeration value="sip-trunking-capability"/>
            <xs:enumeration value="sponsored"/>
            <xs:enumeration value="start"/>
            <xs:enumeration value="status"/>
            <xs:enumeration value="stylesheet"/>
            <xs:enumeration value="subsection"/>
            <xs:enumeration value="successor-version"/>
            <xs:enumeration value="sunset"/>
            <xs:enumeration value="tag"/>
            <xs:enumeration value="terms-of-service"/>
            <xs:enumeration value="timegate"/>
            <xs:enumeration value="timemap"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="ugc"/>
            <xs:enumeration value="up"/>
            <xs:enumeration value="version-history"/>
            <xs:enumeration value="via"/>
            <xs:enumeration value="webmention"/>
            <xs:enumeration value="working-copy"/>
            <xs:enumeration value="working-copy-of"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="strictUriType">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.*"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== alps-asd/app-state-diagram/docs/bookstore/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<alps
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://alps-io.github.io/schemas/alps.xsd">
    <title>オンライン書店カタログシステム2</title>
    <doc>オンライン書店の書籍カタログを管理し、ユーザーの購買フローを定義するためのALPSプロファイル。</doc>
    <link href="https://github.com/example/online-bookstore-api/issues" rel="issue"/>

    <!-- Ontology -->
    <descriptor id="id" def="https://schema.org/identifier" title="識別子"/>
    <descriptor id="title" def="https://schema.org/name" title="タイトル"/>
    <descriptor id="author" def="https://schema.org/author" title="著者"/>
    <descriptor id="isbn" def="https://schema.org/isbn" title="ISBN"/>
    <descriptor id="price" def="https://schema.org/price" title="価格"/>
    <descriptor id="category" def="https://schema.org/category" title="カテゴリー"/>
    <descriptor id="quantity" def="https://schema.org/quantityValue" title="数量"/>
    <descriptor id="totalAmount" def="https://schema.org/totalPrice" title="合計金額"/>
    <descriptor id="userName" def="https://schema.org/name" title="ユーザー名"/>
    <descriptor id="userEmail" def="https://schema.org/email" title="メールアドレス"/>
    <descriptor id="shippingAddress" def="https://schema.org/address" title="配送先住所"/>
    <descriptor id="paymentMethod" def="https://schema.org/paymentMethod" title="支払い方法"/>

    <!-- Taxonomy -->
    <descriptor id="Home" title="ホーム画面">
        <descriptor href="#goToCatalog"/>
        <descriptor href="#goToCart"/>
    </descriptor>

    <descriptor id="Catalog" def="https://schema.org/CollectionPage" title="書籍カタログ" tag="collection">
        <descriptor href="#listBooks"/>
        <descriptor href="#searchBooks"/>
        <descriptor href="#getCategories"/>
        <descriptor href="#goToBookDetails"/>
        <descriptor href="#goToCart"/>
        <descriptor href="#Book"/>
    </descriptor>

    <descriptor id="Book" def="https://schema.org/Book" title="書籍" tag="item">
        <descriptor href="#id"/>
        <descriptor href="#title"/>
        <descriptor href="#author"/>
        <descriptor href="#isbn"/>
        <descriptor href="#price"/>
        <descriptor href="#category"/>
        <descriptor href="#addToCart"/>
        <descriptor href="#goToCatalog"/>
    </descriptor>

    <descriptor id="Category" def="https://schema.org/Category" title="カテゴリー" tag="item">
        <descriptor href="#id"/>
        <descriptor href="#title"/>
    </descriptor>

    <descriptor id="ShoppingCart" def="https://schema.org/ShoppingCart" title="ショッピングカート" tag="collection">
        <descriptor href="#listCartItems"/>
        <descriptor href="#updateQuantity"/>
        <descriptor href="#removeFromCart"/>
        <descriptor href="#goToCheckout"/>
        <descriptor href="#goToCatalog"/>
    </descriptor>

    <descriptor id="Checkout" title="決済画面">
        <descriptor href="#userInfo"/>
        <descriptor href="#shippingInfo"/>
        <descriptor href="#paymentInfo"/>
        <descriptor href="#placeOrder"/>
        <descriptor href="#goToCart"/>
    </descriptor>

    <descriptor id="OrderConfirmation" title="注文確認画面">
        <descriptor href="#orderDetails"/>
        <descriptor href="#goToHome"/>
    </descriptor>

    <!-- Choreography -->
    <descriptor id="goToHome" type="safe" rt="#Home" title="ホーム画面に移動"/>
    <descriptor id="goToCatalog" type="safe" rt="#Catalog" title="カタログ画面に移動"/>
    <descriptor id="goToBookDetails" type="safe" rt="#Book" title="書籍詳細画面に移動">
        <descriptor href="#id"/>
    </descriptor>
    <descriptor id="goToCart" type="safe" rt="#ShoppingCart" title="カート画面に移動"/>
    <descriptor id="goToCheckout" type="safe" rt="#Checkout" title="決済画面に移動"/>

    <descriptor id="listBooks" type="safe" rt="#Catalog" rel="collection" title="書籍一覧の取得">
        <doc>カタログ内のすべての書籍一覧を取得する。ページネーションやソート順の指定が可能。</doc>
    </descriptor>
    <descriptor id="searchBooks" type="safe" rt="#Catalog" rel="collection" title="書籍の検索">
        <doc>指定された検索クエリに基づいて書籍を検索する。</doc>
        <descriptor href="#query"/>
    </descriptor>
    <descriptor id="query" title="検索クエリ">
        <doc>検索に使用するキーワードや条件。</doc>
    </descriptor>
    <descriptor id="getCategories" type="safe" rt="#Catalog" rel="collection" title="カテゴリー一覧の取得">
        <doc>利用可能なすべての書籍カテゴリーの一覧を取得する。</doc>
    </descriptor>
    <descriptor id="getBookDetails" type="safe" rt="#Book" rel="item" title="書籍詳細の取得">
        <doc>指定された書籍IDに基づいて、特定の書籍の詳細情報を取得する。</doc>
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="addToCart" type="unsafe" rt="#ShoppingCart" rel="collection" title="カートに追加">
        <doc>指定された書籍をショッピングカートに追加する。</doc>
        <descriptor href="#id"/>
        <descriptor href="#quantity"/>
    </descriptor>
    <descriptor id="listCartItems" type="safe" rt="#ShoppingCart" rel="collection" title="カート内アイテム一覧の取得"/>
    <descriptor id="updateQuantity" type="idempotent" rt="#ShoppingCart" title="カート内アイテムの数量更新">
        <descriptor href="#id"/>
        <descriptor href="#quantity"/>
    </descriptor>
    <descriptor id="removeFromCart" type="idempotent" rt="#ShoppingCart" title="カートからアイテムを削除">
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="userInfo" type="unsafe" rt="#Checkout" title="ユーザー情報の入力">
        <descriptor href="#userName"/>
        <descriptor href="#userEmail"/>
    </descriptor>
    <descriptor id="shippingInfo" type="unsafe" rt="#Checkout" title="配送情報の入力">
        <descriptor href="#shippingAddress"/>
    </descriptor>
    <descriptor id="paymentInfo" type="unsafe" rt="#Checkout" title="支払い情報の入力">
        <descriptor href="#paymentMethod"/>
    </descriptor>
    <descriptor id="placeOrder" type="unsafe" rt="#OrderConfirmation" title="注文の確定">
        <doc>ユーザーの入力情報を基に注文を確定し、注文確認画面に遷移する。</doc>
    </descriptor>

    <descriptor id="orderDetails" type="safe" rt="#OrderConfirmation" title="注文詳細の表示">
        <doc>確定した注文の詳細情報を表示する。</doc>
    </descriptor>
</alps>

=== alps-asd/app-state-diagram/docs/blog/profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<alps
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="https://alps-io.github.io/schemas/alps.xsd">
    <title>ALPS Blog</title>
    <doc>An ALPS profile example for ASD</doc>
    <link href="https://github.com/koriym/app-state-diagram/issues" rel="issue"/>

    <!-- Ontology -->
    <descriptor id="id" def="https://schema.org/identifier"/>
    <descriptor id="articleBody" def="https://schema.org/articleBody"/>
    <descriptor id="dateCreated" def="https://schema.org/dateCreated"/>

    <!-- Taxonomy -->
    <descriptor id="Index" title="Index Page">
        <descriptor href="#goBlog"/>
    </descriptor>
    <descriptor id="About">
        <descriptor href="#goBlog"/>
    </descriptor>
    <descriptor id="Blog" href="https://schema.org/Blog" title="Blog post list" rel="collection">
        <descriptor href="#goAbout"/>
        <descriptor href="#doPost"/>
        <descriptor href="#goBlogPosting"/>
        <descriptor href="#BlogPosting"/>
    </descriptor>
    <descriptor id="BlogPosting" href="https://schema.org/BlogPosting" title="Blog post item">
        <descriptor href="#id"/>
        <descriptor href="#dateCreated"/>
        <descriptor href="#articleBody"/>
        <descriptor href="#goBlog"/>
    </descriptor>

    <!-- Choreography -->
    <descriptor id="goStart" type="safe" rt="#Blog"/>
    <descriptor id="goAbout" type="safe" rt="#About"/>
    <descriptor id="goBlog" type="safe" rt="#Blog"/>
    <descriptor id="goBlogPosting" type="safe" rt="#BlogPosting">
        <descriptor href="#id"/>
    </descriptor>
    <descriptor id="doPost" def="https://activitystrea.ms/specs/json/1.0/#post-verb" type="unsafe" rt="#Blog">
        <descriptor href="#articleBody"/>
    </descriptor>
</alps>
