=== alps-asd/app-state-diagram/alps.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation source="https://alps.io/spec/index.html">
            A data format for defining simple descriptions of application-level semantics
        </xs:documentation>
        <xs:appinfo source="https://alps.io/spec/index.html"/>
    </xs:annotation>
    <xs:element name="alps" type="alpsType"/>
    <xs:complexType name="alpsType">
        <xs:annotation>
            <xs:documentation>
                A data format for defining simple descriptions of application-level semantics
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="doc" minOccurs="0"/>
                <xs:element ref="link" minOccurs="0"/>
                <xs:element ref="title" minOccurs="0"/>
                <xs:element ref="ext" minOccurs="0"/>
                <xs:element ref="descriptor"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="version" type="xs:string">
            <xs:annotation>
                <xs:documentation> Indicates the version of the ALPS specification used in the document. </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="version" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                Indicates the version of the ALPS specification used in the document.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="doc" type="docType">
        <xs:annotation>
            <xs:documentation>
                A text field that contains free-form, usually human-readable, text.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="title" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                Defines the semantics of specific data elements or state transitions that MAY exist in an associated
                representation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="descriptor" type="descriptorType">
        <xs:annotation>
            <xs:documentation>
                Defines the semantics of specific data elements or state transitions that MAY exist in an associated
                representation.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="link" type="linkType">
        <xs:annotation>
            <xs:documentation>
                An element that identifies a link between the current ALPS element
                and some other (possibly external) resource.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="ext" type="extType">
        <xs:annotation>
            <xs:documentation>
                The 'ext' element can be used to extend the ALPS document with author-specific information.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="contentType" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                A media-type values registered with the IANA.
            </xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="descriptorType" mixed="true">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="descriptor" type="descriptorType" minOccurs="0"/>
                <xs:element name="doc" type="docType" minOccurs="0"/>
                <xs:element name="link" type="linkType" minOccurs="0"/>
            </xs:choice>
        </xs:sequence>
        <!-- documented attribute -->
        <xs:attribute name="href" type="xs:anyURI"/>
        <xs:attribute name="id" type="xs:string"/>
        <xs:attribute name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="semantic"/>
                    <xs:enumeration value="safe"/>
                    <xs:enumeration value="unsafe"/>
                    <xs:enumeration value="idempotent"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="doc" type="xs:string"/>
        <xs:attribute name="ext" type="xs:string"/>
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="rt" type="rtType"/>
        <xs:attribute name="def" type="xs:anyURI"/>
        <xs:attribute name="tag" type="xs:string"/>
        <xs:attribute name="rel" type="relType"/>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="extType">
        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    `ext` element extends the ALPS document with author-specific information.
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
        <xs:attribute name="href" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
        <xs:attribute name="tag" type="xs:string"/>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="linkType">
        <xs:attribute name="rel" type="xs:string"/>
        <xs:attribute name="href" type="xs:anyURI"/>
        <xs:attribute name="tag" type="xs:string"/>
        <xs:attribute name="title" type="xs:string"/>
        <xs:anyAttribute/>
    </xs:complexType>
    <xs:complexType name="docType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="format">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="text"/>
                            <xs:enumeration value="html"/>
                            <xs:enumeration value="asciidoc"/>
                            <xs:enumeration value="markdown"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="contentType" type="xs:string" />
                <xs:attribute name="tag" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="rtType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*#.*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="relType">
        <xs:union memberTypes="predefinedRelType strictUriType"/>
    </xs:simpleType>
    <xs:simpleType name="predefinedRelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="about"/>
            <xs:enumeration value="acl"/>
            <xs:enumeration value="alternate"/>
            <xs:enumeration value="amphtml"/>
            <xs:enumeration value="appendix"/>
            <xs:enumeration value="apple-touch-icon"/>
            <xs:enumeration value="apple-touch-startup-image"/>
            <xs:enumeration value="archives"/>
            <xs:enumeration value="author"/>
            <xs:enumeration value="blocked-by"/>
            <xs:enumeration value="bookmark"/>
            <xs:enumeration value="c2pa-manifest"/>
            <xs:enumeration value="canonical"/>
            <xs:enumeration value="chapter"/>
            <xs:enumeration value="cite-as"/>
            <xs:enumeration value="collection"/>
            <xs:enumeration value="compression-dictionary"/>
            <xs:enumeration value="contents"/>
            <xs:enumeration value="convertedfrom"/>
            <xs:enumeration value="copyright"/>
            <xs:enumeration value="create-form"/>
            <xs:enumeration value="current"/>
            <xs:enumeration value="describedby"/>
            <xs:enumeration value="describes"/>
            <xs:enumeration value="disclosure"/>
            <xs:enumeration value="dns-prefetch"/>
            <xs:enumeration value="duplicate"/>
            <xs:enumeration value="edit"/>
            <xs:enumeration value="edit-form"/>
            <xs:enumeration value="edit-media"/>
            <xs:enumeration value="enclosure"/>
            <xs:enumeration value="external"/>
            <xs:enumeration value="first"/>
            <xs:enumeration value="glossary"/>
            <xs:enumeration value="help"/>
            <xs:enumeration value="hosts"/>
            <xs:enumeration value="hub"/>
            <xs:enumeration value="ice-server"/>
            <xs:enumeration value="icon"/>
            <xs:enumeration value="index"/>
            <xs:enumeration value="intervalafter"/>
            <xs:enumeration value="intervalbefore"/>
            <xs:enumeration value="intervalcontains"/>
            <xs:enumeration value="intervaldisjoint"/>
            <xs:enumeration value="intervalduring"/>
            <xs:enumeration value="intervalequals"/>
            <xs:enumeration value="intervalfinishedby"/>
            <xs:enumeration value="intervalfinishes"/>
            <xs:enumeration value="intervalin"/>
            <xs:enumeration value="intervalmeets"/>
            <xs:enumeration value="intervalmetby"/>
            <xs:enumeration value="intervaloverlappedby"/>
            <xs:enumeration value="intervaloverlaps"/>
            <xs:enumeration value="intervalstartedby"/>
            <xs:enumeration value="intervalstarts"/>
            <xs:enumeration value="item"/>
            <xs:enumeration value="last"/>
            <xs:enumeration value="latest-version"/>
            <xs:enumeration value="license"/>
            <xs:enumeration value="linkset"/>
            <xs:enumeration value="lrdd"/>
            <xs:enumeration value="manifest"/>
            <xs:enumeration value="mask-icon"/>
            <xs:enumeration value="me"/>
            <xs:enumeration value="media-feed"/>
            <xs:enumeration value="memento"/>
            <xs:enumeration value="micropub"/>
            <xs:enumeration value="modulepreload"/>
            <xs:enumeration value="monitor"/>
            <xs:enumeration value="monitor-group"/>
            <xs:enumeration value="next"/>
            <xs:enumeration value="next-archive"/>
            <xs:enumeration value="nofollow"/>
            <xs:enumeration value="noopener"/>
            <xs:enumeration value="noreferrer"/>
            <xs:enumeration value="opener"/>
            <xs:enumeration value="openid2.local_id"/>
            <xs:enumeration value="openid2.provider"/>
            <xs:enumeration value="original"/>
            <xs:enumeration value="p3pv1"/>
            <xs:enumeration value="payment"/>
            <xs:enumeration value="pingback"/>
            <xs:enumeration value="preconnect"/>
            <xs:enumeration value="predecessor-version"/>
            <xs:enumeration value="prefetch"/>
            <xs:enumeration value="preload"/>
            <xs:enumeration value="prerender"/>
            <xs:enumeration value="prev"/>
            <xs:enumeration value="prev-archive"/>
            <xs:enumeration value="preview"/>
            <xs:enumeration value="previous"/>
            <xs:enumeration value="privacy-policy"/>
            <xs:enumeration value="profile"/>
            <xs:enumeration value="publication"/>
            <xs:enumeration value="related"/>
            <xs:enumeration value="replies"/>
            <xs:enumeration value="restconf"/>
            <xs:enumeration value="ruleinput"/>
            <xs:enumeration value="search"/>
            <xs:enumeration value="section"/>
            <xs:enumeration value="self"/>
            <xs:enumeration value="service"/>
            <xs:enumeration value="service-desc"/>
            <xs:enumeration value="service-doc"/>
            <xs:enumeration value="service-meta"/>
            <xs:enumeration value="sip-trunking-capability"/>
            <xs:enumeration value="sponsored"/>
            <xs:enumeration value="start"/>
            <xs:enumeration value="status"/>
            <xs:enumeration value="stylesheet"/>
            <xs:enumeration value="subsection"/>
            <xs:enumeration value="successor-version"/>
            <xs:enumeration value="sunset"/>
            <xs:enumeration value="tag"/>
            <xs:enumeration value="terms-of-service"/>
            <xs:enumeration value="timegate"/>
            <xs:enumeration value="timemap"/>
            <xs:enumeration value="type"/>
            <xs:enumeration value="ugc"/>
            <xs:enumeration value="up"/>
            <xs:enumeration value="version-history"/>
            <xs:enumeration value="via"/>
            <xs:enumeration value="webmention"/>
            <xs:enumeration value="working-copy"/>
            <xs:enumeration value="working-copy-of"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="strictUriType">
        <xs:restriction base="xs:anyURI">
            <xs:pattern value="https?://.*"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== alps-asd/app-state-diagram/docs/bookstore/ja/alps.xml
<?xml version="1.0" encoding="UTF-8"?>
<alps
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://alps-io.github.io/schemas/alps.xsd">
    <title>ALPS Book Store</title>
    <doc>オンライン書店の書籍カタログを管理し、ユーザーの購買フローを定義するためのALPSプロファイル。このプロファイルはRESTfulなAPIとUIの両方のためのセマンティクス定義を提供します。</doc>
    <link href="https://github.com/example/online-bookstore-api/issues" rel="issue"/>

    <!-- オントロジー -->
    <descriptor id="id" def="https://schema.org/identifier" title="識別子" tag="core">
        <doc>各リソースの一意の識別子。UUIDまたは自動採番された整数値。</doc>
    </descriptor>
    <descriptor id="title" def="https://schema.org/name" title="タイトル" tag="catalog">
        <doc>書籍のタイトルまたはカテゴリー名。200文字以内の文字列。</doc>
    </descriptor>
    <descriptor id="author" def="https://schema.org/author" title="著者" tag="catalog">
        <doc>書籍の著者名。複数の著者がいる場合はカンマ区切りで記載。</doc>
    </descriptor>
    <descriptor id="isbn" def="https://schema.org/isbn" title="ISBN" tag="catalog">
        <doc>書籍の国際標準図書番号。ISBN-13形式（ハイフン付き）で記載。</doc>
    </descriptor>
    <descriptor id="price" def="https://schema.org/price" title="価格" tag="commerce">
        <doc>書籍の販売価格。税抜き価格で、通貨単位は円（JPY）。</doc>
    </descriptor>
    <descriptor id="category" def="https://schema.org/category" title="カテゴリー" tag="catalog">
        <doc>書籍のジャンルまたはカテゴリー。複数のカテゴリーに属する場合あり。</doc>
    </descriptor>
    <descriptor id="quantity" def="https://schema.org/quantityValue" title="数量" tag="commerce">
        <doc>カート内の書籍の数量。1以上の整数値。</doc>
    </descriptor>
    <descriptor id="totalAmount" def="https://schema.org/totalPrice" title="合計金額" tag="commerce">
        <doc>注文またはカート内の全商品の合計金額。税込み表示。</doc>
    </descriptor>
    <descriptor id="userName" def="https://schema.org/name" title="ユーザー名" tag="customer">
        <doc>注文者の氏名。姓名をスペースで区切って記載。</doc>
    </descriptor>
    <descriptor id="userEmail" def="https://schema.org/email" title="メールアドレス" tag="customer">
        <doc>注文者の連絡先メールアドレス。注文確認メールの送信先となる。</doc>
    </descriptor>
    <descriptor id="shippingAddress" def="https://schema.org/address" title="配送先住所" tag="shipping">
        <doc>商品の配送先住所。郵便番号、都道府県、市区町村、番地、建物名等を含む。</doc>
    </descriptor>
    <descriptor id="paymentMethod" def="https://schema.org/paymentMethod" title="支払い方法" tag="payment">
        <doc>注文の支払い方法。クレジットカード、代金引換、銀行振込等から選択。</doc>
    </descriptor>
    <descriptor id="query" title="検索クエリ" tag="catalog">
        <doc>書籍検索に使用するキーワードや条件。タイトル、著者名、ISBNなどで検索可能。</doc>
    </descriptor>

    <!-- タクソノミー -->
    <descriptor id="Home" title="ホーム画面" tag="navigation">
        <doc>アプリケーションの開始点となるホーム画面。サイト全体のナビゲーションとプロモーション情報を表示。</doc>
        <descriptor href="#goToCatalog"/>
        <descriptor href="#goToCart"/>
    </descriptor>

    <descriptor id="Catalog" def="https://schema.org/CollectionPage" title="書籍カタログ" tag="catalog">
        <doc>全書籍の一覧表示画面。カテゴリー別フィルタリングやキーワード検索、ソート機能を提供。デフォルトでは新着順に表示。</doc>
        <descriptor href="#goListBooks"/>
        <descriptor href="#goSearchBooks"/>
        <descriptor href="#goGetCategories"/>
        <descriptor href="#goToBookDetails"/>
        <descriptor href="#goToCart"/>
        <descriptor href="#Book"/>
    </descriptor>

    <descriptor id="Book" def="https://schema.org/Book" title="書籍" tag="catalog">
        <doc>個別の書籍情報を表示する画面。詳細情報、レビュー、関連書籍などを表示。この画面からカートに追加可能。</doc>
        <descriptor href="#id"/>
        <descriptor href="#title"/>
        <descriptor href="#author"/>
        <descriptor href="#isbn"/>
        <descriptor href="#price"/>
        <descriptor href="#category"/>
        <descriptor href="#doAddToCart"/>
        <descriptor href="#goToCatalog"/>
    </descriptor>

    <descriptor id="Category" def="https://schema.org/Category" title="カテゴリー" tag="catalog">
        <doc>書籍のジャンル分類。階層構造を持ち、親カテゴリーと子カテゴリーが存在する場合がある。</doc>
        <descriptor href="#id"/>
        <descriptor href="#title"/>
    </descriptor>

    <descriptor id="ShoppingCart" def="https://schema.org/ShoppingCart" title="ショッピングカート" tag="cart">
        <doc>ユーザーが購入予定の書籍が入るカート。数量変更、削除、合計金額の確認ができる。セッションベースで管理。</doc>
        <descriptor href="#goListCartItems"/>
        <descriptor href="#doUpdateQuantity"/>
        <descriptor href="#doRemoveFromCart"/>
        <descriptor href="#goToCheckout"/>
        <descriptor href="#goToCatalog"/>
    </descriptor>

    <descriptor id="Checkout" title="決済画面" tag="checkout">
        <doc>購入手続き画面。ユーザー情報、配送先、支払い方法を入力する。注文確定前に最終確認を表示。</doc>
        <descriptor href="#doUserInfo"/>
        <descriptor href="#doShippingInfo"/>
        <descriptor href="#doPaymentInfo"/>
        <descriptor href="#doPlaceOrder"/>
        <descriptor href="#goToCart"/>
    </descriptor>

    <descriptor id="OrderConfirmation" title="注文確認画面" tag="order">
        <doc>注文完了後の確認画面。注文番号、合計金額、配送予定日等の情報を表示。確認メールが自動送信される。</doc>
        <descriptor href="#goOrderDetails"/>
        <descriptor href="#goToHome"/>
    </descriptor>

    <!-- コレオグラフィー -->
    <descriptor id="goToHome" type="safe" rt="#Home" title="ホーム画面に移動">
        <doc>アプリケーションのホーム画面に遷移する。どの画面からでもアクセス可能。</doc>
    </descriptor>
    <descriptor id="goToCatalog" type="safe" rt="#Catalog" title="カタログ画面に移動">
        <doc>書籍カタログ一覧画面に遷移する。全書籍が表示される。</doc>
    </descriptor>
    <descriptor id="goToBookDetails" type="safe" rt="#Book" title="書籍詳細画面に移動">
        <doc>選択した書籍の詳細情報画面に遷移する。書籍IDを指定する必要がある。</doc>
        <descriptor href="#id"/>
    </descriptor>
    <descriptor id="goToCart" type="safe" rt="#ShoppingCart" title="カート画面に移動">
        <doc>現在のショッピングカートの内容を表示する画面に遷移する。</doc>
    </descriptor>
    <descriptor id="goToCheckout" type="safe" rt="#Checkout" title="決済画面に移動">
        <doc>カートの内容を確認し、購入手続きを行う画面に遷移する。カートが空の場合は遷移できない。</doc>
    </descriptor>

    <descriptor id="goListBooks" type="safe" rt="#Catalog" rel="collection" title="書籍一覧の取得" tag="catalog">
        <doc>カタログ内のすべての書籍一覧を取得する。ページネーション（デフォルト20件/ページ）やソート順（新着順、価格順、人気順等）の指定が可能。</doc>
    </descriptor>
    <descriptor id="goSearchBooks" type="safe" rt="#Catalog" rel="collection" title="書籍の検索" tag="catalog">
        <doc>指定された検索クエリに基づいて書籍を検索する。タイトル、著者名、内容説明、ISBNなどの複数フィールドから検索可能。</doc>
        <descriptor href="#query"/>
    </descriptor>
    <descriptor id="goGetCategories" type="safe" rt="#Catalog" rel="collection" title="カテゴリー一覧の取得" tag="catalog">
        <doc>利用可能なすべての書籍カテゴリーの一覧を取得する。階層構造を持つカテゴリーの場合は親子関係も返される。</doc>
    </descriptor>
    <descriptor id="goGetBookDetails" type="safe" rt="#Book" rel="item" title="書籍詳細の取得" tag="catalog">
        <doc>指定された書籍IDに基づいて、特定の書籍の詳細情報を取得する。在庫状況や関連書籍の情報も含まれる。</doc>
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="doAddToCart" type="unsafe" rt="#ShoppingCart" rel="collection" title="カートに追加" tag="cart">
        <doc>指定された書籍をショッピングカートに追加する。既にカートに存在する場合は数量が加算される。在庫数を超える注文はエラーとなる。</doc>
        <descriptor href="#id"/>
        <descriptor href="#quantity"/>
    </descriptor>
    <descriptor id="goListCartItems" type="safe" rt="#ShoppingCart" rel="collection" title="カート内アイテム一覧の取得" tag="cart">
        <doc>現在のショッピングカート内のすべての商品と、その数量、小計、合計金額を取得する。</doc>
    </descriptor>
    <descriptor id="doUpdateQuantity" type="idempotent" rt="#ShoppingCart" title="カート内アイテムの数量更新" tag="cart">
        <doc>カート内の特定商品の数量を更新する。0以下の数値は指定できない。在庫数を超える数量はエラーとなる。</doc>
        <descriptor href="#id"/>
        <descriptor href="#quantity"/>
    </descriptor>
    <descriptor id="doRemoveFromCart" type="idempotent" rt="#ShoppingCart" title="カートからアイテムを削除" tag="cart">
        <doc>指定されたアイテムをカートから完全に削除する。該当アイテムがカートに存在しない場合は何も変更されない。</doc>
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="doUserInfo" type="unsafe" rt="#Checkout" title="ユーザー情報の入力" tag="customer">
        <doc>注文者の氏名とメールアドレスを入力する。メールアドレスは正規表現による検証が行われる。</doc>
        <descriptor href="#userName"/>
        <descriptor href="#userEmail"/>
    </descriptor>
    <descriptor id="doShippingInfo" type="unsafe" rt="#Checkout" title="配送情報の入力" tag="shipping">
        <doc>商品の配送先住所を入力する。郵便番号検索による住所自動入力機能あり。</doc>
        <descriptor href="#shippingAddress"/>
    </descriptor>
    <descriptor id="doPaymentInfo" type="unsafe" rt="#Checkout" title="支払い情報の入力" tag="payment">
        <doc>注文の支払い方法を選択し、必要な支払い情報を入力する。クレジットカード選択時はカード情報の入力と検証を行う。</doc>
        <descriptor href="#paymentMethod"/>
    </descriptor>
    <descriptor id="doPlaceOrder" type="unsafe" rt="#OrderConfirmation" title="注文の確定" tag="order">
        <doc>ユーザーの入力情報を基に注文を確定し、注文確認画面に遷移する。支払い処理が実行され、在庫が確保される。この操作は取り消せない。</doc>
    </descriptor>

    <descriptor id="goOrderDetails" type="safe" rt="#OrderConfirmation" title="注文詳細の表示" tag="order">
        <doc>確定した注文の詳細情報を表示する。注文番号、購入商品一覧、合計金額、配送先、支払い方法などが含まれる。</doc>
    </descriptor>
</alps>

=== alps-asd/app-state-diagram/docs/mini-commerce/alps.xml
<?xml version="1.0" encoding="UTF-8"?>
<alps
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://alps-io.github.io/schemas/alps.xsd">
    <title>app-state-diagram</title>
    <doc>This is a sample ALPS profile demonstrating the semantic descriptors and operations for a basic e-commerce system. It includes product listing, shopping cart management, and checkout process, serving as an educational example for ALPS implementation in online shopping contexts.</doc>

    <!-- Ontology -->
    <descriptor id="id" def="https://schema.org/identifier" title="identifier"/>
    <descriptor id="name" def="https://schema.org/name" title="name"/>
    <descriptor id="description" def="https://schema.org/description" title="description"/>
    <descriptor id="price" def="https://schema.org/price" title="price"/>
    <descriptor id="quantity" def="https://schema.org/Quantity" title="quantity"/>
    <descriptor id="email" def="https://schema.org/email" title="email"/>
    <descriptor id="address" def="https://schema.org/address" title="address"/>

    <!-- Taxonomy -->
    <descriptor id="ProductList" def="https://schema.org/ItemList" title="Product List" tag="collection">
        <doc>Displays a list of available products that the user can browse or select from.</doc>
        <descriptor href="#id"/>
        <descriptor href="#name"/>
        <descriptor href="#description"/>
        <descriptor href="#goProductDetail"/>
        <descriptor href="#goCart"/>
        <descriptor href="#goProductList"/>
    </descriptor>

    <descriptor id="ProductDetail" def="https://schema.org/Product" title="Product Detail" tag="item">
        <doc>MAX:Shows detailed information about a single product, such as description and price.Shows detailed information about a single product, such as description and price.Shows detailed information about a single product, such as description and price.Shows detailed information about a single product, such as description and price.Shows detailed information about a single product, such as description and price.Shows detailed information about a single product, such as description and price.Shows detailed information about a single product, such as description and price.</doc>
        <descriptor href="#id"/>
        <descriptor href="#name"/>
        <descriptor href="#description"/>
        <descriptor href="#price"/>
        <descriptor href="#goProductList"/>
        <descriptor href="#doAddToCart"/>
    </descriptor>

    <descriptor id="Cart" def="https://schema.org/Cart" title="Shopping Cart" tag="collection">
        <doc>Displays the user's shopping cart, allowing updates or checkout initiation.</doc>
        <descriptor href="#id"/>
        <descriptor href="#goProductList"/>
        <descriptor href="#goCheckout"/>
        <descriptor href="#doUpdateQuantity"/>
        <descriptor href="#doRemoveItem"/>
    </descriptor>

    <descriptor id="Checkout" title="Checkout" tag="collection">
        <doc>Captures user information and prepares for payment after shopping is complete.</doc>
        <descriptor href="#email"/>
        <descriptor href="#address"/>
        <descriptor href="#goPayment"/>
    </descriptor>

    <descriptor id="Payment" def="https://schema.org/PayAction" title="Payment" tag="item">
        <doc>Handles the final payment process for the placed order.</doc>
        <descriptor href="#doPayment"/>
    </descriptor>

    <!-- Choreography -->
    <descriptor id="goProductList" type="safe" rt="#ProductList" title="View product list">
        <doc>Returns the list of all available products.</doc>
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="goProductDetail" type="safe" rt="#ProductDetail" title="View product details">
        <doc>Returns detailed view of a selected product.</doc>
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="goCart" type="safe" rt="#Cart" title="View shopping cart">
        <doc>Displays the current items in the user's shopping cart.</doc>
    </descriptor>

    <descriptor id="goCheckout" type="safe" rt="#Checkout" title="Proceed to checkout">
        <doc>Initiates the checkout process after confirming cart items.</doc>
    </descriptor>

    <descriptor id="goPayment" type="safe" rt="#Payment" title="Proceed to payment">
        <doc>Redirects user to the payment screen after entering delivery details.</doc>
    </descriptor>

    <descriptor id="doAddToCart" type="unsafe" rt="#Cart" title="Add product to cart">
        <doc>Adds selected product and quantity to the shopping cart.</doc>
        <descriptor href="#id"/>
        <descriptor href="#quantity"/>
    </descriptor>

    <descriptor id="doUpdateQuantity" type="idempotent" rt="#Cart" title="Update item quantity">
        <doc>Updates the quantity of a product already in the cart.</doc>
        <descriptor href="#id"/>
        <descriptor href="#quantity"/>
    </descriptor>

    <descriptor id="doRemoveItem" type="idempotent" rt="#Cart" title="Remove item from cart">
        <doc>Removes a specific product from the shopping cart.</doc>
        <descriptor href="#id"/>
    </descriptor>

    <descriptor id="doPayment" type="idempotent" rt="#ProductList" title="Complete payment">
        <doc>Processes the final payment and returns user to the product list.</doc>
    </descriptor>
</alps>

=== alps-asd/app-state-diagram/tests/Fake/alps.title.xml
<?xml version="1.0" encoding="UTF-8"?>
<alps
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://alps-io.github.io/schemas/alps.xsd">
    <descriptor id="Home" title="Home">
        <descriptor href="#goState" />
    </descriptor>
    <descriptor id="State" title="State">
        <descriptor href="#goNext" />
        <descriptor href="#goPrev" />
    </descriptor>
    <descriptor id="goState" title="go state" type="safe" rt="#State" />
    <descriptor id="goNext" title="go next state" type="safe" rt="#State" />
    <descriptor id="goPrev" title="go prev state" type="safe" rt="#State" />
</alps>
