=== alps-asd/app-state-diagram/docs/asd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>ALPS ASD config</xs:documentation>
        <xs:appinfo source="https://github.com/alps-asd/app-state-diagram"/>
    </xs:annotation>
    <xs:element name="asd">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="alpsFile"/>
                <xs:element ref="watch"/>
                <xs:element ref="port"/>
                <xs:element ref="filter"/>
                <xs:element ref="label"/>
                <xs:element ref="mode"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name="alpsFile" type="xs:string">
        <xs:annotation>
            <xs:documentation>ALPS profile file path</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="watch" type="xs:boolean">
        <xs:annotation>
            <xs:documentation>Rendering in watch mode</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="port" default="3000">
        <xs:annotation>
            <xs:documentation>Watch mode server port</xs:documentation>
        </xs:annotation>
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1024"/>
                <xs:maxInclusive value="49151"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="filter" type="filterType" >
        <xs:annotation>
            <xs:documentation>Filter list</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="mode" type="modeType">
        <xs:annotation>
            <xs:documentation>Output formart</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="filterType">
        <xs:sequence>
            <xs:element name="and" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="or" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="color" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="label" type="labelType" >
        <xs:annotation>
            <xs:documentation>Display text label</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:simpleType name="labelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="id"/>
            <xs:enumeration value="title"/>
            <xs:enumeration value="both"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="modeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="html"/>
            <xs:enumeration value="markdown"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== alps-asd/app-state-diagram/tests/Fake/config/asd.xml
<?xml version="1.0"?>
<asd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../../../docs/asd.xsd">
    <alpsFile>profile.xml</alpsFile>
    <watch>false</watch>
    <port>3000</port>
    <filter>
        <and>tag1</and>
        <and>tag2</and>
        <or>tag3</or>
    </filter>
    <mode>markdown</mode>
</asd>
